---
    name: PR To main (or master) merged
    on:
      pull_request:
        branches:
          - main
        types:
          - closed
    jobs:
      build-push:
        if: ${{ github.event.pull_request.merged }}
        uses: ./.github/workflows/reusable_build-push.yml
        with:
          name: '${{ github.event.repository.name }}'
          tags: latest-rc
        secrets: inherit
    