---
name: Manual build and push image
on:
  workflow_dispatch:
jobs:
    build-push-image:
        uses: ./.github/workflows/reusable_build-push.yml
        with:
          name: '${{ github.event.repository.name }}'
          tags: 'manual-${{ github.ref_name }}'
    