---
    name: Manual build and push image
    on:
      workflow_dispatch:
    jobs:
        build-image:
            runs-on: ubuntu-latest
            steps:
                - name: Check out GitHub Repo
                  uses: actions/checkout@v4

                - name: Get current date
                  id: date
                  run: echo "::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

                - name: Set up Docker Buildx
                  uses: docker/setup-buildx-action@v2

                - name: Login to GHCR
                  uses: docker/login-action@v2
                  with:
                      registry: ghcr.io
                      username: '${{ secrets.GHCR_USERNAME }}'
                      password: '${{ secrets.GHCR_TOKEN }}'

                - name: Extract metadata 
                  id: meta
                  uses: docker/metadata-action@v5
                  with:
                      images: ghcr.io/eapearson/kbase-orcidlink-utils

                - name: Build and push
                  uses: docker/build-push-action@v5
                  with:
                      context: .
                      file: ./Dockerfile
                      push: true
                      build-args: |
                          BUILD_DATE=${{ steps.date.outputs.date }}
                          VCS_REF=${{ github.sha }}
                          BRANCH='${{ github.ref }}'
                          TAG='${{ github.ref }}'
                      labels: '${{ steps.meta.outputs.labels }}'
                      tags: '${{ steps.meta.outputs.tags}}'
    