---
    name: PR to main
    on:
      pull_request:
        branches:
          - main
        types:
          - opened
          - reopened
          - synchronize
    jobs:
        build-image:
            runs-on: ubuntu-latest
            steps:
                - name: Check out GitHub Repo
                  uses: actions/checkout@v3

                - name: Get current date
                  id: date
                  run: echo "::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

                - name: Set up Docker Buildx
                  uses: docker/setup-buildx-action@v2

                - name: Login to GHCR
                  uses: docker/login-action@v2
                  with:
                      registry: ghcr.io
                      username: '${{ secrets.GHCR_USERNAME }}'
                      password: '${{ secrets.GHCR_TOKEN }}'

                - name: Build and push
                  uses: docker/build-push-action@v3
                  with:
                      context: .
                      file: ./Dockerfile
                      pull: true
                      push: true
                      build-args: |
                          BUILD_DATE=${{ steps.date.outputs.date }}
                          VCS_REF=${{ github.sha }}
                          BRANCH='${{ github.ref }}'
                          TAG='${{ github.ref }}'
                      tags: pr-${{ github.event.number }}
    