---
name: PR to main build and push image
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
jobs:
    build-push-image:
      uses: ./.github/workflows/reusable_build-push.yml
      with:
        name: '${{ github.event.repository.name }}'
        tags: 'pr-${{ github.event.number }}'
      secrets: inherit
    